services:
  # Catalog Service API (using GCP Cloud SQL)
  catalog-service:
    build:
      context: ../CatalogService
    container_name: catalog-service
    env_file:
      - .env
    ports:
      - "7083:8080"
    networks:
      - supermarket-network
    restart: unless-stopped

  # Shopping App Frontend
  shopping-app:
    build: 
      context: ../shopping-app
      args:
        REACT_APP_CATALOG_API_URL: http://localhost:7083/api
    container_name: online-supermarket-shopping-app
    ports:
      - "3000:80"
    depends_on:
      - catalog-service
    environment:
      - NODE_ENV=production
    networks:
      - supermarket-network
    restart: unless-stopped
  # Order Management Service
  order-management:
    image: ilani/order-management:latest
    container_name: order-management
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "3001:3000"
    networks:
      - supermarket-network
    restart: unless-stopped

networks:
  supermarket-network:
    driver: bridge
